# Generated by Django 4.2 on 2023-05-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_data_crud', '0002_data_2_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_mahasiwa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=150)),
                ('nim', models.CharField(max_length=100)),
                ('fakultas', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=100)),
                ('nilai_sikap', models.IntegerField()),
                ('nilai_uts', models.IntegerField()),
                ('nilai_uas', models.IntegerField()),
            ],
        ),
    ]
